### PR TITLE
Issues/#26 async http

### PR DESCRIPTION
**Pull request by elsamuko**

### CODE REVIEW

**Comment by tholu** [comment]
@mattab Any idea why the check hasn't been completed here yet? The build was successful at Travis (https://travis-ci.org/github/matomo-org/piwik-java-tracker/builds/665191664) - tried multiple times. As I don't have access to settings, I can't debug further or disable the check for this PR (if it's a temporary Travis bug).

**Comment by mattab** [comment]
@tholu Not sure what is the issue, but the build at https://travis-ci.org/github/matomo-org/piwik-java-tracker/builds/665191664 shows "success". If you need "Admin" permission on the repo please let me know?

**Comment by tholu** [comment]
@mattab If you can give me this level of access, I’ll try to dig deeper. Curiously it worked fine for my own pull request. Thank you!

**Comment by tholu** [comment]
Closing in favor of #31, as it seems that Travis has problems with dealing with # in branch names.

**Pull request closed without merging**
